version: '3.5'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=guy
      - POSTGRES_DB=algo-flash-cards
    container_name: database
    volumes:
      - algo-pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - '8000:3000'
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src
  
  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      FLASHCARD_API_HOST: http://localhost:8000

volumes:
  algo-pgdata:
    external: true
